"""
report_generator.py
Converts a SessionLogger into:
  • A Markdown report string (for UI display + download)
  • A JSON dump (for programmatic consumption)
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from utils.logger import SessionLogger


# ── Severity emoji mapping ─────────────────────────────────────────────────────

_SEV_ICON = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
}


class ReportGenerator:
    """
    Generates human-readable and machine-readable reports from a session.

    Usage::

        rg = ReportGenerator(session_logger)
        md_text = rg.to_markdown()
        json_text = rg.to_json()
        rg.save(output_dir="reports/output")
    """

    def __init__(self, session: SessionLogger):
        self._s = session

    # ── Markdown ──────────────────────────────────────────────────────────

    def to_markdown(self) -> str:
        s = self._s
        lines: list[str] = []

        # Header
        lines += [
            "# FailSafe AI — Simulation Report",
            "",
            f"**Session ID:** `{s.session_id}`  ",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total tests run | {s.total} |",
            f"| Failures detected | {s.failed} |",
            f"| Unexpected passes | {s.passed_count} |",
            f"| Critical failures | {s.critical_count} |",
            "",
        ]

        # Severity breakdown
        sev = s.severity_breakdown()
        if sev:
            lines += ["### Severity Breakdown", ""]
            for severity, count in sorted(sev.items()):
                icon = _SEV_ICON.get(severity, "⚪")
                lines.append(f"- {icon} **{severity.capitalize()}**: {count}")
            lines.append("")

        # Category breakdown
        cat = s.category_breakdown()
        if cat:
            lines += ["### Failure Categories", ""]
            for category, count in sorted(cat.items(), key=lambda x: -x[1]):
                lines.append(f"- `{category}`: {count} occurrence(s)")
            lines.append("")

        lines += ["---", "", "## Test Results", ""]

        # Individual test entries
        for i, entry in enumerate(s.entries, start=1):
            status = "✅ PASS" if entry.passed else "❌ FAIL"
            sev_icon = _SEV_ICON.get(entry.severity, "⚪")

            lines += [
                f"### Test {i}: `{entry.injection_name}` — {status}",
                "",
                f"**Scenario:** {entry.scenario}",
                "",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| Error type | `{entry.error_type or 'None'}` |",
                f"| Severity | {sev_icon} {entry.severity} |",
                f"| Category | {entry.category} |",
                f"| Execution time | {entry.execution_time_ms:.1f} ms |",
                f"| Timed out | {'Yes ⏱' if entry.timed_out else 'No'} |",
                "",
            ]

            if entry.error_message:
                lines += [
                    f"**Error message:** `{entry.error_message}`",
                    "",
                ]

            lines += [
                "**Root cause analysis:**",
                f"> {entry.root_cause}",
                "",
                "**Recommended fix:**",
                f"> {entry.short_fix}",
                "",
            ]

            if entry.ollama_enhanced:
                lines += [
                    "**🤖 AI-enhanced explanation (Ollama):**",
                    f"> {entry.ollama_enhanced}",
                    "",
                ]

            lines.append("---")
            lines.append("")

        # Footer
        lines += [
            "",
            "*Report generated by FailSafe AI — System Failure Simulator & Debug Assistant*",
        ]

        return "\n".join(lines)

    # ── JSON ──────────────────────────────────────────────────────────────

    def to_json(self) -> str:
        return json.dumps(self._s.to_dict(), indent=2)

    # ── Save ──────────────────────────────────────────────────────────────

    def save(self, output_dir: str | Path = "reports/output") -> dict[str, Path]:
        """
        Write markdown + JSON reports to disk.
        Returns a dict with keys 'markdown' and 'json' pointing to the files.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        sid = self._s.session_id
        md_path = out / f"report_{sid}.md"
        json_path = out / f"report_{sid}.json"

        md_path.write_text(self.to_markdown(), encoding="utf-8")
        json_path.write_text(self.to_json(), encoding="utf-8")

        return {"markdown": md_path, "json": json_path}
